# Generated by Django 4.0 on 2023-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='updated_at',
        ),
    ]
