# Generated by Django 4.0 on 2023-05-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0002_remove_adminhod_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentResult',
            new_name='StudentGrade',
        ),
    ]
