# Generated by Django 4.0 on 2023-05-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0003_rename_studentresult_studentgrade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='ClassGroup',
        ),
    ]
