# Generated by Django 4.0 on 2023-05-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0006_rename_adminhod_admin_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionYearModel',
            new_name='SchoolYear',
        ),
    ]
