# Generated by Django 4.0 on 2023-05-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0007_rename_sessionyearmodel_schoolyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolyear',
            old_name='session_end_year',
            new_name='school_end_year',
        ),
        migrations.RenameField(
            model_name='schoolyear',
            old_name='session_start_year',
            new_name='school_start_year',
        ),
    ]
