# Generated by Django 4.0 on 2023-05-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0008_rename_session_end_year_schoolyear_school_end_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='session_year_id',
            new_name='school_year_id',
        ),
    ]
