# Generated by Django 4.0 on 2023-05-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0009_rename_session_year_id_students_school_year_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='session_year_id',
            new_name='school_year_id',
        ),
    ]
