# Generated by Django 4.0 on 2023-05-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0010_rename_session_year_id_attendance_school_year_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='school_year_id',
            new_name='session_year_id',
        ),
        migrations.RenameField(
            model_name='schoolyear',
            old_name='school_end_year',
            new_name='session_end_year',
        ),
        migrations.RenameField(
            model_name='schoolyear',
            old_name='school_start_year',
            new_name='session_start_year',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='school_year_id',
            new_name='session_year_id',
        ),
    ]
