# Generated by Django 4.0 on 2023-05-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0011_rename_school_year_id_attendance_session_year_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrade',
            old_name='subject_assignment_marks',
            new_name='subject_exam_points',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='subject_exam_marks',
        ),
    ]
