# Generated by Django 4.0 on 2023-05-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0012_rename_subject_assignment_marks_studentgrade_subject_exam_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='class_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='class_id',
            new_name='course_id',
        ),
    ]
