# Generated by Django 4.0 on 2023-05-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0013_rename_class_id_students_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='course_id',
            new_name='class_id',
        ),
    ]
