# Generated by Django 4.0 on 2023-05-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0015_rename_course_id_subjects_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classgroup',
            old_name='course_name',
            new_name='class_name',
        ),
    ]
