# Generated by Django 4.0 on 2023-05-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0016_rename_course_name_classgroup_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolyear',
            old_name='session_start_year',
            new_name='school_start',
        ),
    ]
