# Generated by Django 4.0 on 2023-05-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0017_rename_session_start_year_schoolyear_school_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolyear',
            old_name='session_end_year',
            new_name='schooly_end',
        ),
    ]
