# Generated by Django 4.0 on 2023-05-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0018_rename_session_end_year_schoolyear_schooly_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='session_year_id',
            new_name='school_year_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='session_year_id',
            new_name='school_year_id',
        ),
    ]
